apiVersion: v1
kind: ResourceQuota
metadata: # kpt-merge: example/default
  name: default
  namespace: backend1
  annotations:
    internal.kpt.dev/upstream-identifier: '|ResourceQuota|example|default'
spec:
  hard:
    cpu: "2"
    memory: 4G
